@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedHireME" as VersionedHireME MODEL_COLOR
end box

[-> Model : undoHireME()
activate Model

Model -> VersionedHireME : undo()
activate VersionedHireME

VersionedHireME -> VersionedHireME :resetData(ReadOnlyHireME)
VersionedHireME --> Model :
deactivate VersionedHireME

[<-- Model
deactivate Model

@enduml
